package com.joshlong.mogul.api.utils.jdbc;

import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;
import org.springframework.aop.SpringProxy;
import org.springframework.aop.framework.Advised;
import org.springframework.aot.hint.MemberCategory;
import org.springframework.aot.hint.RuntimeHints;
import org.springframework.aot.hint.RuntimeHintsRegistrar;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.ImportRuntimeHints;
import org.springframework.core.DecoratingProxy;

import java.sql.ResultSet;

@Configuration
@ImportRuntimeHints(ReplayableResultSetsAutoConfiguration.Hints.class)
class ReplayableResultSetsAutoConfiguration {

	/**
	 * proxies generated by {@link ReplayableResultSets} need to be registered with
	 * GraalVM
	 */
	static class Hints implements RuntimeHintsRegistrar {

		@Override
		public void registerHints(@NonNull RuntimeHints hints, @Nullable ClassLoader classLoader) {

			var classes = new Class<?>[] { AutoCloseable.class, ReplayableResultSet.class, ResultSet.class,
					SpringProxy.class, Advised.class, DecoratingProxy.class };

			hints.proxies().registerJdkProxy(classes);

			var mc = MemberCategory.values();
			for (var c : classes)
				hints.reflection().registerType(c, mc);

		}

	}

}
